vich_uploader:
    db_driver: orm

    mappings:
        document_files:
            uri_prefix: /uploads/excel
            upload_destination: '%kernel.project_dir%/public/uploads/excel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer